---
- hosts: all
  become: true
  tasks:

    - name: "Install apache"
      apt:
        name: apache2
        update_cache: true
        state: latest

    - name: "Start service apache"
      service:
        name: apache2
        state: started
